version: '3.8'

networks:
  red_pawbnb:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.1.0/24
          gateway: 172.28.1.1

services:
  php:
    build:
      context: ./config/php
    ports:
      - 9000:9000
    volumes:
      - ./web:/srv/www/api
      - ./config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    links:
      - db
    networks:
      red_pawbnb:
        ipv4_address: 172.28.1.2

  nginx:
    image: nginx:latest
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./web:/srv/www/api
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/certificados:/etc/nginx/conf.d/certificados:ro
    depends_on:
      - php
    networks:
      red_pawbnb:
        ipv4_address: 172.28.1.3

  pma:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - ${IP}:8000:80
    depends_on:
      - db
    networks:
      red_pawbnb:
        ipv4_address: 172.28.1.4

  db:
    image: mariadb:latest
    ports:
      - "${IP}:3306:3306"
    command: ["--init-file", "/docker-entrypoint-initdb.d/init.sql"]
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    networks:
      red_pawbnb:
        ipv4_address: 172.28.1.5
volumes:
  db_data:
